/* tslint:disable */
/* eslint-disable */
/**
 * LIT.Smabu.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Currency } from './currency';
import { FinancialCategory } from './financial-category';
import { PaymentCondition } from './payment-condition';
import { PaymentMethod } from './payment-method';
import { TaxRate } from './tax-rate';
import { Unit } from './unit';
 /**
 * 
 *
 * @export
 * @interface EnumsResponse
 */
export interface EnumsResponse {

    /**
     * @type {Array<Currency>}
     * @memberof EnumsResponse
     */
    currencies: Array<Currency> | null;

    /**
     * @type {Array<PaymentMethod>}
     * @memberof EnumsResponse
     */
    paymentMethods: Array<PaymentMethod> | null;

    /**
     * @type {Array<PaymentCondition>}
     * @memberof EnumsResponse
     */
    paymentConditions: Array<PaymentCondition> | null;

    /**
     * @type {Array<Unit>}
     * @memberof EnumsResponse
     */
    units: Array<Unit> | null;

    /**
     * @type {Array<FinancialCategory>}
     * @memberof EnumsResponse
     */
    financialCategoryIncomes: Array<FinancialCategory> | null;

    /**
     * @type {Array<FinancialCategory>}
     * @memberof EnumsResponse
     */
    financialCategoryExpenditures: Array<FinancialCategory> | null;

    /**
     * @type {Array<TaxRate>}
     * @memberof EnumsResponse
     */
    taxRates: Array<TaxRate> | null;
}
