/* tslint:disable */
/* eslint-disable */
/**
 * LIT.Smabu.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { FinancialCategory } from './financial-category';
import { PaymentId } from './payment-id';
 /**
 * 
 *
 * @export
 * @interface FinancialTransaction
 */
export interface FinancialTransaction {

    /**
     * @type {Date}
     * @memberof FinancialTransaction
     */
    date?: Date;

    /**
     * @type {number}
     * @memberof FinancialTransaction
     */
    amount?: number;

    /**
     * @type {string}
     * @memberof FinancialTransaction
     */
    description?: string | null;

    /**
     * @type {FinancialCategory}
     * @memberof FinancialTransaction
     */
    category?: FinancialCategory;

    /**
     * @type {PaymentId}
     * @memberof FinancialTransaction
     */
    paymentId?: PaymentId;

    /**
     * @type {boolean}
     * @memberof FinancialTransaction
     */
    isImported?: boolean;
}
