/* tslint:disable */
/* eslint-disable */
/**
 * LIT.Smabu.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InvoiceDTO } from './invoice-dto';
import { PaymentDTO } from './payment-dto';

/**
 * 
 *
 * @export
 * @interface GetInvoiceDTO
 * @extends {InvoiceDTO}
 */
export interface GetInvoiceDTO extends InvoiceDTO {

    /**
     * @type {Array<PaymentDTO>}
     * @memberof GetInvoiceDTO
     */
    payments: Array<PaymentDTO>;

    /**
     * @type {boolean}
     * @memberof GetInvoiceDTO
     */
    isPaid: boolean;
}