/* tslint:disable */
/* eslint-disable */
/**
 * LIT.Smabu.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AnnualFinancialStatementId } from './annual-financial-statement-id';
import { FinancialTransaction } from './financial-transaction';
 /**
 * 
 *
 * @export
 * @interface UpdateAnnualFinancialStatementCommand
 */
export interface UpdateAnnualFinancialStatementCommand {

    /**
     * @type {AnnualFinancialStatementId}
     * @memberof UpdateAnnualFinancialStatementCommand
     */
    annualFinancialStatementId?: AnnualFinancialStatementId;

    /**
     * @type {Array<FinancialTransaction>}
     * @memberof UpdateAnnualFinancialStatementCommand
     */
    incomes?: Array<FinancialTransaction> | null;

    /**
     * @type {Array<FinancialTransaction>}
     * @memberof UpdateAnnualFinancialStatementCommand
     */
    expenditures?: Array<FinancialTransaction> | null;
}
