/* tslint:disable */
/* eslint-disable */
/**
 * LIT.Smabu.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PaymentCondition } from './payment-condition';
import { PaymentId } from './payment-id';
import { PaymentMethod } from './payment-method';
import { PaymentStatus } from './payment-status';
 /**
 * 
 *
 * @export
 * @interface UpdatePaymentCommand
 */
export interface UpdatePaymentCommand {

    /**
     * @type {PaymentId}
     * @memberof UpdatePaymentCommand
     */
    paymentId?: PaymentId;

    /**
     * @type {string}
     * @memberof UpdatePaymentCommand
     */
    details?: string | null;

    /**
     * @type {string}
     * @memberof UpdatePaymentCommand
     */
    payer?: string | null;

    /**
     * @type {string}
     * @memberof UpdatePaymentCommand
     */
    payee?: string | null;

    /**
     * @type {string}
     * @memberof UpdatePaymentCommand
     */
    referenceNr?: string | null;

    /**
     * @type {Date}
     * @memberof UpdatePaymentCommand
     */
    referenceDate?: Date | null;

    /**
     * @type {Date}
     * @memberof UpdatePaymentCommand
     */
    accountingDate?: Date;

    /**
     * @type {number}
     * @memberof UpdatePaymentCommand
     */
    amountDue?: number;

    /**
     * @type {Date}
     * @memberof UpdatePaymentCommand
     */
    dueDate?: Date | null;

    /**
     * @type {PaymentMethod}
     * @memberof UpdatePaymentCommand
     */
    paymentMethod?: PaymentMethod;

    /**
     * @type {PaymentStatus}
     * @memberof UpdatePaymentCommand
     */
    status?: PaymentStatus;

    /**
     * @type {PaymentCondition}
     * @memberof UpdatePaymentCommand
     */
    paymentCondition?: PaymentCondition;
}
